[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
daoverse = "D11BbTWnpBwXfRC3WibZwkDFhGMdbGxVHWD76DU14eJd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
